---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-mcp
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: unifi-mcp-secret
    creationPolicy: Owner
  data:
    - secretKey: UNIFI_API_KEY
      remoteRef:
        key: Unifi Controller
        property: unifi_mcp_server
