---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unleashed-voucher-manager
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: unleashed-voucher-manager-secret
    creationPolicy: Owner
  data:
    - secretKey: UNLEASHED_USERNAME
      remoteRef:
        key: Ruckus Unleashed Controller
        property: username
    - secretKey: UNLEASHED_PASSWORD
      remoteRef:
        key: Ruckus Unleashed Controller
        property: password
