---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unimus-backup-exporter
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: unimus-backup-exporter-secret
    creationPolicy: Owner
  data:
    - secretKey: UNIMUS_API_KEY
      remoteRef:
        key: unimus
        property: api_key
    - secretKey: DO_SPACES_ACCESS_KEY
      remoteRef:
        key: DigitalOcean
        property: unimus_spaces_access_key
    - secretKey: DO_SPACES_SECRET_KEY
      remoteRef:
        key: DigitalOcean
        property: unimus_spaces_secret_key
