---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unimus-backup-exporter-backups
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-zfs
