---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bmc-cert-updater-supermicro
spec:
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
    - name: external-secrets
      namespace: external-secrets
    - name: internal-greyrock-io-cert
  interval: 1h
  path: "./kubernetes/apps/network/bmc-cert-updater-supermicro/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: network
