---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: towonel-agent
spec:
  endpoints:
    - dnsName: ingress-ext.greyrock.io
      recordType: A
      targets:
        - &vps_ip 161.35.252.109
    - dnsName: twnl.greyrock.io
      recordType: A
      targets:
        - *vps_ip
    - dnsName: skedaddle-doco-cd.greyrock.io
      recordType: A
      targets:
        - *vps_ip
    - dnsName: skedaddle-gatus.greyrock.io
      recordType: A
      targets:
        - *vps_ip
