---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: doorbell-cert-updater-reolink
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: doorbell-cert-updater-reolink-secret
    creationPolicy: Owner
  data:
    - secretKey: UPDATER_USERNAME
      remoteRef:
        key: BMC Certs
        property: updater-username
    - secretKey: REOLINK_PASSWORD
      remoteRef:
        key: BMC Certs
        property: courtyard-porch-doorbell
