---
# yaml-language-server: $schema=https://k8s-schemas.greyrock.io/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: devices
spec:
  module: icmp
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - basement-iotawatt.internal.greyrock.io
        - brouhaha.internal.greyrock.io
        - bumfuzzle.internal.greyrock.io
        - codswallop.internal.greyrock.io
        - garage-iotawatt.internal.greyrock.io
        - homeassistant.internal.greyrock.io
        - kerfuffle.internal.greyrock.io
        - kvm-brouhaha.internal.greyrock.io
        - kvm-bumfuzzle.internal.greyrock.io
        - kvm-homeassistant.internal.greyrock.io
        - kvm-kerfuffle.internal.greyrock.io
        - kvm-nas.internal.greyrock.io
        - time1.internal.greyrock.io
        - time2.internal.greyrock.io
        - time3.internal.greyrock.io
        - time4.internal.greyrock.io
        - tubeszb-efr32-mgm24-2023.internal.greyrock.io
        - tubeszb-zw.internal.greyrock.io
---
# yaml-language-server: $schema=https://k8s-schemas.greyrock.io/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: nfs
spec:
  jobName: nfs_probe
  module: tcp_connect
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - codswallop.internal.greyrock.io:2049
