---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: devices
spec:
  module: icmp
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - bambu-a1-printer.internal.greyrock.io
        - codswallop.internal.greyrock.io
        - gameroom-ap.internal.greyrock.io
        - gameroom-c08pf.internal.greyrock.io
        - gameroom-c08zp.internal.greyrock.io
        - gameroom-crs309.internal.greyrock.io
        - garage-ap.internal.greyrock.io
        - garage-c08pf.internal.greyrock.io
        - garage-c08zp.internal.greyrock.io
        - garage-crs309.internal.greyrock.io
        - home.internal.greyrock.io
        - iotabase.internal.greyrock.io
        - iotagrge.internal.greyrock.io
        - kitchen-ap.internal.greyrock.io
        # - livingroom-ap.internal.greyrock.io
        - office-ap.internal.greyrock.io
        - office-c08pf.internal.greyrock.io
        - office-c08zp.internal.greyrock.io
        - office-crs309.internal.greyrock.io
        - office-gw.internal.greyrock.io
        - rear-driveway-ap.internal.greyrock.io
        - side-driveway-ap.internal.greyrock.io
        - side-yard-ap.internal.greyrock.io
        - time1.internal.greyrock.io
        - time2.internal.greyrock.io
        - time3.internal.greyrock.io
        - time4.internal.greyrock.io
        - upstairs-hallway-ap.internal.greyrock.io
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: nfs
spec:
  jobName: nfs_probe
  module: tcp_connect
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - codswallop.internal.greyrock.io:2049
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: tls-certs
spec:
  jobName: tls_cert_probe
  module: http_2xx_insecure_tls
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - https://home.internal.greyrock.io
