---
# yaml-language-server: $schema=https://k8s-schemas.greyrock.io/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager-webhook-cloudns
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cert-manager-webhook-cloudns-api-secret
    creationPolicy: Owner
  data:
    - secretKey: auth_id
      remoteRef:
        key: ClouDNS
        property: cert-manager-auth-id
    - secretKey: auth_password
      remoteRef:
        key: ClouDNS
        property: cert-manager-auth-password
