---
# yaml-language-server: $schema=https://k8s-schemas.greyrock.io/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-webhook-cloudns
spec:
  chartRef:
    kind: OCIRepository
    name: cert-manager-webhook-cloudns
  interval: 30m
  values:
    certManager:
      namespace: cert-manager
      serviceAccountName: cert-manager
    clouDNS:
      authIdType: auth-id
      credentialsDir: /creds
    groupName: acme.ixon.cloud
    podAnnotations:
      secret.reloader.stakater.com/reload: cert-manager-webhook-cloudns-api-secret
    resources:
      requests:
        cpu: 10m
        memory: 32M
      limits:
        memory: 64M
    secretName: cert-manager-webhook-cloudns-api-secret
