---
services:
  bootimus:
    container_name: bootimus
    image: garybowers/bootimus:0.1.76
    mac_address: 4a:f0:ea:98:ae:5b
    restart: unless-stopped
    environment:
      BOOTIMUS_PROXY_DHCP_ENABLED: "true"
      BOOTIMUS_SERVER_ADDR: 10.1.20.2
    volumes:
      - data:/data
    networks:
      lan:
        ipv4_address: 10.1.20.2
volumes:
  data:
    driver: local
    driver_opts:
      device: /mnt/tank/apps/bootimus/data
      o: bind
      type: none
networks:
  lan:
    driver: macvlan
    driver_opts:
      parent: enp1s0f0
    ipam:
      config:
        - subnet: 10.1.20.0/24
