---
# yaml-language-server: $schema=https://k8s-schemas.greyrock.io/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: externaldns-cloudns
spec:
  chartRef:
    kind: OCIRepository
    name: externaldns-cloudns
  interval: 30m
  values:
    fullnameOverride: externaldns-cloudns
    logLevel: &logLevel info
    domainFilters:
      - greyrock.io
    podAnnotations:
      secret.reloader.stakater.com/reload: externaldns-cloudns-secret
    policy: sync
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/rwunderer/external-dns-cloudns-webhook
          tag: v0.4.10@sha256:b8a16baa5e53fc90dc6a885b5e7e48d98613465818662b2752dd3cd0132c49a4
        env:
          - name: LOG_LEVEL
            value: *logLevel
          - name: CLOUDNS_AUTH_ID_TYPE
            value: auth-id
          - name: CLOUDNS_AUTH_ID
            valueFrom:
              secretKeyRef:
                name: externaldns-cloudns-secret
                key: auth_id
          - name: CLOUDNS_AUTH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: externaldns-cloudns-secret
                key: auth_password
        securityContext:
          runAsUser: 65532
          runAsGroup: 65532
        livenessProbe:
          httpGet:
            path: /health
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
    resources:
      requests:
        cpu: 13m
        memory: 42M
      limits:
        memory: 42M
    serviceMonitor:
      enabled: false
    extraArgs:
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
      - --gateway-name=envoy-external
      - --webhook-provider-url=http://localhost:8888
    sources:
      - crd
      - gateway-httproute
    triggerLoopOnEvent: true
    txtOwnerId: main
    txtPrefix: k8s.main.%{record_type}-
