---
endpoints:
  - name: skedaddle | ping
    group: vps
    url: icmp://161.35.252.109
    interval: 1m
    ui:
      hide-url: true
      hide-hostname: true
    conditions:
      - "[CONNECTED] == true"
