---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bmc-cert-updater-asrock
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: bmc-cert-updater-asrock-secret
    creationPolicy: Owner
  data:
    - secretKey: UPDATER_USERNAME
      remoteRef:
        key: Cert Updater
        property: updater-username
    - secretKey: CODSWALLOP_PASSWORD
      remoteRef:
        key: Cert Updater
        property: codswallop-password
    - secretKey: KERFUFFLE_PASSWORD
      remoteRef:
        key: Cert Updater
        property: kerfuffle-password
