---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oxidized
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: oxidized-secret
    creationPolicy: Owner
  data:
    - secretKey: OXIDIZED_USERNAME
      remoteRef:
        key: oxidized
        property: OXIDIZED_USERNAME
    - secretKey: OXIDIZED_PASSWORD
      remoteRef:
        key: oxidized
        property: OXIDIZED_PASSWORD
