---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oxidized
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: oxidized-secret
    creationPolicy: Owner
  data:
    - secretKey: ssh_private_key
      remoteRef:
        key: oxidized
        property: ssh_private_key
    - secretKey: forgejo_known_hosts
      remoteRef:
        key: oxidized
        property: forgejo_known_hosts
    - secretKey: do_spaces_access_key_id
      remoteRef:
        key: DigitalOcean
        property: oxidized_do_spaces_access_key_id
    - secretKey: do_spaces_secret_access_key
      remoteRef:
        key: DigitalOcean
        property: oxidized_do_spaces_secret_access_key
    - secretKey: do_spaces_endpoint
      remoteRef:
        key: DigitalOcean
        property: oxidized_do_spaces_endpoint
    - secretKey: do_spaces_bucket
      remoteRef:
        key: DigitalOcean
        property: oxidized_do_spaces_bucket
