---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oxidized
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: oxidized-secret
    creationPolicy: Owner
  data:
    - secretKey: ssh_private_key
      remoteRef:
        key: oxidized
        property: ssh_private_key
    - secretKey: s3_access_key_id
      remoteRef:
        key: oxidized
        property: s3_access_key_id
    - secretKey: s3_secret_access_key
      remoteRef:
        key: oxidized
        property: s3_secret_access_key
    - secretKey: s3_endpoint
      remoteRef:
        key: oxidized
        property: s3_endpoint
    - secretKey: s3_bucket
      remoteRef:
        key: oxidized
        property: s3_bucket
