---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oxidized
spec:
  chartRef:
    kind: OCIRepository
    name: oxidized
  interval: 30m
  values:
    controllers:
      oxidized:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            fsGroup: 30000
        containers:
          app:
            image:
              repository: docker.io/oxidized/oxidized
              tag: 0.31.0
            env:
              OXIDIZED_HOME: /oxidized
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 60
                  timeoutSeconds: 10
                  failureThreshold: 5
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
    service:
      app:
        ports:
          http:
            port: 8888
    persistence:
      config:
        type: configMap
        name: oxidized-config
        globalMounts:
          - path: /oxidized/config
            subPath: config
      router-db:
        type: configMap
        name: oxidized-config
        globalMounts:
          - path: /oxidized/router.db
            subPath: router.db
      ssh-key:
        type: secret
        name: oxidized-secret
        defaultMode: 0644
        globalMounts:
          - path: /home/oxidized/.ssh/id_rsa
            subPath: ssh_private_key
          - path: /home/oxidized/.ssh/id_rsa.pub
            subPath: ssh_public_key
      ssh-known-hosts:
        type: secret
        name: oxidized-secret
        globalMounts:
          - path: /home/oxidized/.ssh/known_hosts
            subPath: forgejo_known_hosts
      workdir:
        type: emptyDir
        globalMounts:
          - path: /oxidized
      backups:
        existingClaim: oxidized-backups
        globalMounts:
          - path: /data/network-backups
