---
# yaml-language-server: $schema=https://k8s-schemas.greyrock.io/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: externaldns-digitalocean
spec:
  chartRef:
    kind: OCIRepository
    name: externaldns-digitalocean
  interval: 30m
  values:
    fullnameOverride: externaldns-digitalocean
    logLevel: &logLevel info
    domainFilters:
      - greyrock.io
    podAnnotations:
      secret.reloader.stakater.com/reload: externaldns-digitalocean-secret
    policy: sync
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/amoniacou/external-dns-digitalocean-webhook
          tag: 0.1.3
        env:
          - name: LOG_LEVEL
            value: *logLevel
          - name: DO_TOKEN
            valueFrom:
              secretKeyRef:
                name: externaldns-digitalocean-secret
                key: api_token
        securityContext:
          runAsUser: 65532
          runAsGroup: 65532
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8888
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8888
          initialDelaySeconds: 10
          timeoutSeconds: 5
    resources:
      requests:
        cpu: 13m
        memory: 42M
      limits:
        memory: 42M
    serviceMonitor:
      enabled: false
    extraArgs:
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
      - --gateway-name=envoy-external
    sources:
      - crd
      - gateway-httproute
    triggerLoopOnEvent: true
    txtOwnerId: main
    txtPrefix: "k8s."
