---
customization:
  extraKernelArgs:
    - initcall_blacklist=algif_aead_init
  systemExtensions:
    officialExtensions:
      - siderolabs/i915-ucode
      - siderolabs/intel-npu
      - siderolabs/intel-ucode
      - siderolabs/zfs
