---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: localca
spec:
  chartRef:
    kind: OCIRepository
    name: localca
  interval: 30m
  values:
    controllers:
      localca:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          migrate:
            image:
              repository: docker.io/practicalsre/local-ca
              tag: latest
            command:
              - sh
              - -c
              - python manage.py migrate && python manage.py initadmin
            env:
              CSRF_TRUSTED_ORIGINS: https://certs.greyrock.io
        containers:
          app:
            image:
              repository: docker.io/practicalsre/local-ca
              tag: latest
            command:
              - python
              - manage.py
              - runserver
              - 0.0.0.0:8000
            env:
              CSRF_TRUSTED_ORIGINS: https://certs.greyrock.io
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 256Mi

    persistence:
      db:
        existingClaim: localca
        globalMounts:
          - path: /app/db

    route:
      app:
        hostnames:
          - certs.greyrock.io
        parentRefs:
          - name: envoy-internal
            namespace: network

    service:
      app:
        ports:
          http:
            port: 8000
