---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: externaldns-firewalla
spec:
  chartRef:
    kind: OCIRepository
    name: externaldns-firewalla
  interval: 30m
  values:
    fullnameOverride: externaldns-firewalla
    logLevel: &logLevel info
    domainFilters:
      - greyrock.io
    podAnnotations:
      secret.reloader.stakater.com/reload: externaldns-firewalla-secret
    policy: sync
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/theoutdoorprogrammer/external-dns-firewalla-webhook
          tag: 1.1.0
        env:
          - name: LOG_LEVEL
            value: *logLevel
          - name: FIREWALLA_HOST
            value: 10.1.20.1
          - name: FIREWALLA_PROVIDER_PORT
            value: "8888"
          - name: FIREWALLA_HEALTH_PORT
            value: "8080"
          - name: WEBHOOK_PORT
            value: "8888"
          - name: METRICS_PORT
            value: "8080"
          - name: SHARED_SECRET
            valueFrom:
              secretKeyRef:
                name: externaldns-firewalla-secret
                key: shared-secret
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 5
    resources:
      requests:
        cpu: 16m
        memory: 90M
      limits:
        memory: 90M
    serviceMonitor:
      enabled: true
    extraArgs:
      - --gateway-name=envoy-internal
    sources:
      - gateway-httproute
      - service
    triggerLoopOnEvent: true
    txtOwnerId: main
    txtPrefix: "k8s."
