---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: forgejo
spec:
  kanidmRef:
    name: kanidm
  displayname: Forgejo
  origin: https://git.greyrock.io/
  redirectUrl:
    - https://git.greyrock.io/user/oauth2/kanidm/callback
  scopeMap:
    - group: forgejo_admins@idm.greyrock.io
      scopes:
        - openid
        - profile
        - email
        - groups
    - group: forgejo_users@idm.greyrock.io
      scopes:
        - openid
        - profile
        - email
        - groups
  strictRedirectUrl: true
  preferShortUsername: true
  disableConsentPrompt: true
