---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: externaldns-opnsense
spec:
  chartRef:
    kind: OCIRepository
    name: externaldns-opnsense
  interval: 30m
  values:
    fullnameOverride: externaldns-opnsense
    logLevel: &logLevel info
    domainFilters:
      - greyrock.io
    podAnnotations:
      secret.reloader.stakater.com/reload: externaldns-opnsense-secret
    policy: sync
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/crutonjohn/external-dns-opnsense-webhook
          tag: v1.0.0
        env:
          - name: LOG_LEVEL
            value: *logLevel
          - name: OPNSENSE_HOST
            value: https://10.1.0.1
          - name: OPNSENSE_SKIP_TLS_VERIFY
            value: "true"
          - name: SERVER_HOST
            value: 0.0.0.0
          - name: OPNSENSE_API_KEY
            valueFrom:
              secretKeyRef:
                name: externaldns-opnsense-secret
                key: api-key
          - name: OPNSENSE_API_SECRET
            valueFrom:
              secretKeyRef:
                name: externaldns-opnsense-secret
                key: api-secret
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 5
    resources:
      requests:
        cpu: 16m
        memory: 90M
      limits:
        memory: 90M
    serviceMonitor:
      enabled: true
    sources:
      - gateway-httproute
      - service
    triggerLoopOnEvent: true
    txtOwnerId: main
    txtPrefix: "k8s."
