---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
components:
  - ../../components/flux-alerts
  - ../../components/kopiur/secret
  - ../../components/namespace
resources:
  - ./bmc-cert-updater-asrock/ks.yaml
  - ./bmc-cert-updater-supermicro/ks.yaml
  - ./doorbell-cert-updater-reolink/ks.yaml
  - ./echo-server/ks.yaml
  - ./envoy-gateway/ks.yaml
  - ./external-dns/ks.yaml
  - ./internal-greyrock-io-cert/ks.yaml
  - ./multus/ks.yaml
  - ./printer-cert-updater-brother/ks.yaml
  - ./towonel-agent/ks.yaml
  - ./unleashed-voucher-manager/ks.yaml
  - ./wifi-cert-updater-ruckus/ks.yaml
